In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.21.5'

In [42]:
df = pd.read_csv('data.csv')

In [6]:
df.shape

(11914, 16)

In [22]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [35]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [38]:
median = df['Engine Cylinders'].median()

In [37]:
df['Engine Cylinders'].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [39]:
most_frequent = 4.0

In [40]:
df['Engine Cylinders'].fillna(most_frequent)

0        6.0
1        6.0
2        6.0
3        6.0
4        6.0
        ... 
11909    6.0
11910    6.0
11911    6.0
11912    6.0
11913    6.0
Name: Engine Cylinders, Length: 11914, dtype: float64

In [41]:
df['Engine Cylinders'].median()

6.0

In [44]:
df_lotus = df[df['Make'] == 'Lotus']

In [46]:
df2 = df_lotus[['Engine HP', 'Engine Cylinders']].drop_duplicates()

In [49]:
x = df2.to_numpy()

In [50]:
x

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [51]:
xt = np.transpose(x)

In [53]:
XTX = np.matmul(xt,x)

In [54]:
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [55]:
INVXTX = np.linalg.inv(XTX)

In [56]:
INVXTX

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [58]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [59]:
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [61]:
res = np.matmul(INVXTX,xt)

In [62]:
w = np.matmul(res,y)

In [63]:
w

array([  4.59494481, -63.56432501])